# Generated by Django 4.0 on 2024-04-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kino_odi', models.CharField(max_length=100)),
                ('qoshimcha', models.TextField()),
                ('kod', models.IntegerField()),
                ('silka', models.CharField(max_length=255)),
            ],
        ),
    ]
